sudo: required

services:
  - docker

before_install:
  - docker build -t matisq/jenkins-slave .
  - wget https://goss.rocks/install
  - chmod 777 install
  - sudo ./install

script:
  - pwd
  - ls -lthr
  - sudo mkdir /goss
  - cp -rvp /home/travis/build/matisku/jenkins-slave/goss.yaml /goss
  - #dgoss run matisq/jenkins-slave
