version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t matisq/jenkins-slave:$CIRCLE_BRANCH .
     - run: docker run -i -p 222:22 matisq/jenkins-slave:$CIRCLE_BRANCH java -version
